### ISSUE TITLE
.idea should be gitignored

### ISSUE THREAD

**Issue by steve-kaufman** [qhdwight/frc-go#2]
Hi @qhdwight , I'm looking to contribute to your repository and help make things a bit more robust. This is kind of a petty issue, but I'm a little bit of a coding clean freak, so here's where I'll start.

I also like to make lots and lots of issues to track progress, so I hope that doesn't get annoying. You should consider making a GitHub project using the Automated Kanban template, so you can view open issues, pr's, and closed issues in nice little 'To Do', 'In Progress', and 'Done' columns.

**Comment by qhdwight** [comment]
Hi @steve-kaufman, first thank you for your interest! I actually graduated from highschool last year and am off to college, so it may make sense to fork this repository and start your own project. You can set up the issues and complete the prs there. Best of luck! And let me know if you have any questions I'll try my best to help out.
